telegram.api-url: "https://api.telegram.org/"
telegram.user:  <@MyBot_NextBot>
telegram.token: <5151417157:AAEQS72cJv2z6ddXgwakFVyTLvJTjPlgQYs>
telegram.webhook-path: <?? ???? ????>
server.port: <?? ???? ????>

spring.redis.database: 0
spring.redis.host: <???? ?? Redis>
spring.redis.port: <???? ?? Redis>
spring.redis.password: <?????? ?? Redis>
spring.redis.ssl: true
